### PR TITLE
Use Pick type to define Class prototype.

### LINKED ISSUE #696: [Bug]: Class declaration is broken
I found that the `Class` declaration is broken.

In [this](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDCAbAhgZxwHgBUAaOAQSgHMBXAW2ADsYc5QZGATF6hgawYgB3BgG0AunAC8cLA0TiAfFLgBvAFBw4YKBBi7kwAFxxCAbg1wGwQXAAUAOkdYqdRswD6xijXpMcASmMzNQBfczUAY2w8ciJlHn4hBiV1TQA3LAxqIxNwzQiIBhwYKGoIvShbDKycwn9VC00YAAsASxx7auzlLuBzTRDQtTVWpmAoADMsCNQAIQA1TIbNCdbgDA5jBjoAI3HzQcjollm4tk4TxYxlBcylc4YuWMIU4cOo3BY0M5B2R5YyK9NKNirIZkE8nACkUSmUKrYojhjJhPkQFPVUpoEG0OiCYGDUNIrDZEbYVHBVutNnAAIwABjgIX8-UZQzUGSgMmUxPQtlmzLUQA) example:
```ts
export type Class<T, Arguments extends unknown[] = any[]> = {
  prototype: T;
  new (...arguments_: Arguments): T;
};

class A<T = unknown> {
  value: T;

  constructor(value: T) {
    this.value = value;
  }
}

interface BVal {
  field: number;
}

class B<T extends BVal = BVal> extends A<T> {

}

class C<T extends A> {
  instance: T;

  constructor(cls: Class<T>) {
    this.instance = new cls({ field: 10 });
  }
}

var a = new C(B);
```
the type of `a` is not `C<B<BVal>>` as I expected, but `C<B<any>>`, which breaks the type inference.

After some investigation I found that it was caused by using the `T` generic as a value for the `prototype` property. It is incorrect because the prototype in `constructor` should be the parent class, not the instance of the declaring class. That's why TypeScript fails to infer the correct type.

If I change `prototype` type to `object`, `a` has the correct type `C<B<BVal>>`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/696">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/696/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by ajvincent**
Fixes #696 .

### CODE REVIEW

**Comment by ajvincent** [comment]
@Lodin I could use a little more help.  I copied your test for `Class` (thank you very much for that), using better names, but I couldn't immediately come up with a good abstract class test in this scenario.

**Comment by sindresorhus** [comment]
@ajvincent Maybe ChatGPT can help. Can you try out this? https://chat.openai.com/share/232f2043-f201-40c6-8b7a-1fb8b9b96c80

**Comment by ajvincent** [comment]
> @ajvincent Maybe ChatGPT can help. Can you try out this? https://chat.openai.com/share/232f2043-f201-40c6-8b7a-1fb8b9b96c80

No good.  The problem is their test also passes under the old `AbstractClass` type.  The same is true for any test case I can imagine.

(Sorry for the lengthy delay.  I've been exceedingly busy in the last few weeks.)

**Comment by ajvincent** [comment]
[Obligatory playground link](https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.2.2#code/JYWwDg9gTgLgBAbwFBzgQQEYGcZQIYDGMAwhAHY5QCuR0SAvnAGZQQhwBEMAnmAKYBaJnxwcA3EiShIsRHwAe-ImixZgAczJ4MAGz4AaOAqUwAolFZRDxvkQByEGCrWbte64tswAKrz6MWNjgAchgsABNgiSRjaHgefjgASSw0Mm4AHm8APjgAXjgABiN5GD4ycKw4AEY4ADI4bzgAfjhcKj44AC5mPB0sPmiEzuIdPFUAeR1wrMM0KHUqEHKwkrKKqqoyAGsyCAB3MgBtAF18uDx009yC5ABIMFYYRz8e7wk7sj59gAoAOgBeAWSxWWAA+j15otlmQwgBKN4SehDPxwUbjLB2b6zdDAmGrBTrSpwLa7A7HM4FS7ca7ne6PRwvfg9AAKwAI2xx2z43AgTEa2Q+X1+AL+QOhoIhuIlsKwCMaSOisVkwzRY1UOKhINla3KxNJe0Op3O1NpeRQbWonUJeqq7U6zQt6NUWP2mrxoNyXSd6qwUxm3jmHtlgskBF9cAAQlRgNNgGR1Flzgbybl7uS+FAsIikHcCORKDRnlAfhgY3GExNDpns404Yhc3cYAALYBYP4ZrPnMux8Lx9RVr5Zj70BiSVXEcpYKhVW65-NbGA9MhLDCZxVhiMACQgM74GUHmdIi91GzRU5n50nFBnuRtZ+jvf7B+rUGPsLTo6Q4YxaOAPEjHQIA5DJHwrdRfESe9iTAvsEzTXMoBEYBwnKAg+B6WD+0gwZJDzAt2loEsdxnbDXjVDFQPLOCIL8QwjmvacsBObJ63uJtW3bJC1FQsh0POYU4BItQExwn4EAXWEegAJnoOERzHb8CLgAAxPAQFjbhzh+QTiH-bhAOA7YfmEvg4ThP5uJQtC+A7V8sAkGwiBwjIUjSTJhj5VT1M07Jsh+Jg+gGeSYk8ZRVA0LRdH3FcQDXKB-LUjSdG4P5JJgEKpFhTNAv4zBKEIEhfX9d0ZQJUpbRJHZDQpE0rhY09iXy3BCtIChCOLUrtTCBCHieJkMIVRT4zKKBcs6Zr8CIZ1MWxQNpW6qpoM2aryWNKl6rvCqz0m1qCOoIiuvxLBeoZZ5hlZdlOXm7leX5HIkUkZV4lRXbpt9I7QUalaySNSkLk284LUC-prW24l7RaC03qKjFXU+kNujgaHsBa96MRK+atWO0MkAAejxuAABE+CYeNOkuC5Uam+Af1UJBtAKog4DpqoYawhMkwKFNDgQ1BUE7Wt3kkfmWf2otoFLaj+0PLM3jYi1RdQFs2zsodZzgHtwNlhzFbgL9RYJ9AyBKdSwD0KmmfgZYWwgcI2mbPBrZneA1zgaQ9HxPh7YwLTpwwVmRD1xm0dpvoCCoMYygAWTwEbykudDSBwLAfnlWL4se-HCbQMW+KQso4H91nGv7B2KepwqWYjS57Y9vh8TLlsK6tuAbebO2sG-CM2vCCAcVlkmYDj-pvsQMXF2XVdM31raiTZyuiA5xNB74YfYxOhtRfzdqDuLH5BZ6Vf1-6BWlf56d+BLQWQtFg3+aNpJwE9lYm+bFvQ7bteO-CPWCHDyOTs+Cx3jloPifBk5hDTlPOKM9kDn1QI-Z+DcVhO2AOQOAqET5VHfkhP4qloCm2QYYf8E9pia06BgcY3s4AYObnADOM8vKCz+HrUWBcqBQBNirdsLD0pwAAFQ1EKIUMQcAjbeE4u7KoAArF2FxMFLBAFpf+OgI5R3QWQVhd9FJGxJmTL4CimBbCIJoh2TsSgmCqJTEONNq6-mGEgYxfEYBmIIEhIBy8kjtUTvuLGCwlrgx+jVa4Pw9bLxmpCResMNT+PUCdfQetRTilrFCLu8omjwIfoTAAyvGfi+xOj-zIKEd2PjYTACAQDS2n8S59iQkQFKhg9ZG3oWADENCOARN9BwIuHdI4+wpnndxa8ikRmgmXGx0T7GqG0dkuAAABMIAgnIwBWRYOg7C16cJNoJbpGJ-iAgCSFL8RtiAeNcQmap8YcC+NofyYIvcIDBBJCJdQ5cQgjM8dLBM3jbngJec40x5BWE7xwG3bgTzzhfLKF48p6EfhPMMAgCeUk4AAFZ9YhVWS5Ny6RXLwr4C5Ty-J2Y-PUH5fyINgqOTCk4CKrhooZEYQlH4yinlqxrGlXcsJMpGwcPsQw7LyB9zgPsXc5C3aUxucPcB9y0QiogIYWucBeRUD6RKwZVMLbPEwRAb0YKIB6D+EBdQbLIWKrSgAqOwC47ZTAUnCAKc07yXEbk-p5DdwwDAFQeA6KRHu35IU5gRqgL7A+eEJRKjrVoIwaa9krCgA)

**Comment by sindresorhus** [comment]
@Emiyaaaaa Any ideas? ⬆️

**Comment by Emiyaaaaa** [comment]
> @Emiyaaaaa Any ideas? ⬆️

Looks like it's been resolved by @ajvincent 👍

**Comment by sindresorhus** [comment]
@Emiyaaaaa No. It's still missing a test, as mentioned.

> The problem is their test also passes under the current AbstractClass type. The same is true for any test case I can imagine.

:arrow_up:

**Comment by Emiyaaaaa** [comment]
> [Obligatory playground link](https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.2.2#code/JYWwDg9gTgLgBAbwFBzgQQEYGcZQIYDGMAwhAHY5QCuR0SAvnAGZQQhwBEMAnmAKYBaJnxwcA3EiShIsRHwAe-ImixZgAczJ4MAGz4AaOAqUwAolFZRDxvkQByEGCrWbte64tswAKrz6MWNjgAchgsABNgiSRjaHgefjgASSw0Mm4AHm8APjgAXjgABiN5GD4ycKw4AEY4ADI4bzgAfjhcKj44AC5mPB0sPmiEzuIdPFUAeR1wrMM0KHUqEHKwkrKKqqoyAGsyCAB3MgBtAF18uDx009yC5ABIMFYYRz8e7wk7sj59gAoAOgBeAWSxWWAA+j15otlmQwgBKN4SehDPxwUbjLB2b6zdDAmGrBTrSpwLa7A7HM4FS7ca7ne6PRwvfg9AAKwAI2xx2z43AgTEa2Q+X1+AL+QOhoIhuIlsKwCMaSOisVkwzRY1UOKhINla3KxNJe0Op3O1NpeRQbWonUJeqq7U6zQt6NUWP2mrxoNyXSd6qwUxm3jmHtlgskBF9cAAQlRgNNgGR1Flzgbybl7uS+FAsIikHcCORKDRnlAfhgY3GExNDpns404Yhc3cYAALYBYP4ZrPnMux8Lx9RVr5Zj70BiSVXEcpYKhVW65-NbGA9MhLDCZxVhiMACQgM74GUHmdIi91GzRU5n50nFBnuRtZ+jvf7B+rUGPsLTo6Q4YxaOAPEjHQIA5DJHwrdRfESe9iTAvsEzTXMoBEYBwnKAg+B6WD+0gwZJDzAt2loEsdxnbDXjVDFQPLOCIL8QwjmvacsBObJ63uJtW3bJC1FQsh0POYU4BItQExwn4EAXWEegAJnoOERzHb8CLgAAxPAQFjbhzh+QTiH-bhAOA7YfmEvg4ThP5uJQtC+A7V8sAkGwiBwjIUjSTJhj5VT1M07Jsh+Jg+gGeSYk8ZRVA0LRdH3FcQDXKB-LUjSdG4P5JJgEKpFhTNAv4zBKEIEhfX9d0ZQJUpbRJHZDQpE0rhY09iXy3BCtIChCOLUrtTCBCHieJkMIVRT4zKKBcs6Zr8CIZ1MWxQNpW6qpoM2aryWNKl6rvCqz0m1qCOoIiuvxLBeoZZ5hlZdlOXm7leX5HIkUkZV4lRXbpt9I7QUalaySNSkLk284LUC-prW24l7RaC03qKjFXU+kNujgaHsBa96MRK+atWO0MkAAejxuAABE+CYeNOkuC5Uam+Af1UJBtAKog4DpqoYawhMkwKFNDgQ1BUE7Wt3kkfmWf2otoFLaj+0PLM3jYi1RdQFs2zsodZzgHtwNlhzFbgL9RYJ9AyBKdSwD0KmmfgZYWwgcI2mbPBrZneA1zgaQ9HxPh7YwLTpwwVmRD1xm0dpvoCCoMYygAWTwEbykudDSBwLAfnlWL4se-HCbQMW+KQso4H91nGv7B2KepwqWYjS57Y9vh8TLlsK6tuAbebO2sG-CM2vCCAcVlkmYDj-pvsQMXF2XVdM31raiTZyuiA5xNB74YfYxOhtRfzdqDuLH5BZ6Vf1-6BWlf56d+BLQWQtFg3+aNpJwE9lYm+bFvQ7bteO-CPWCHDyOTs+Cx3jloPifBk5hDTlPOKM9kDn1QI-Z+DcVhO2AOQOAqET5VHfkhP4qloCm2QYYf8E9pia06BgcY3s4AYObnADOM8vKCz+HrUWBcqBQBNirdsLD0pwAAFQ1EKIUMQcAjbeE4u7KoAArF2FxMFLBAFpf+OgI5R3QWQVhd9FJGxJmTL4CimBbCIJoh2TsSgmCqJTEONNq6-mGEgYxfEYBmIIEhIBy8kjtUTvuLGCwlrgx+jVa4Pw9bLxmpCResMNT+PUCdfQetRTilrFCLu8omjwIfoTAAyvGfi+xOj-zIKEd2PjYTACAQDS2n8S59iQkQFKhg9ZG3oWADENCOARN9BwIuHdI4+wpnndxa8ikRmgmXGx0T7GqG0dkuAAABMIAgnIwBWRYOg7C16cJNoJbpGJ-iAgCSFL8RtiAeNcQmap8YcC+NofyYIvcIDBBJCJdQ5cQgjM8dLBM3jbngJec40x5BWE7xwG3bgTzzhfLKF48p6EfhPMMAgCeUk4AAFZ9YhVWS5Ny6RXLwr4C5Ty-J2Y-PUH5fyINgqOTCk4CKrhooZEYQlH4yinlqxrGlXcsJMpGwcPsQw7LyB9zgPsXc5C3aUxucPcB9y0QiogIYWucBeRUD6RKwZVMLbPEwRAb0YKIB6D+EBdQbLIWKrSgAqOwC47ZTAUnCAKc07yXEbk-p5DdwwDAFQeA6KRHu35IU5gRqgL7A+eEJRKjrVoIwaa9krCgA)

Resolved here @sindresorhus

**Comment by ajvincent** [comment]
No, no, no, it had not been resolved.  I posted that while I was still wandering around in the weeds.

The solution came to me while I was away from my desk yesterday: only the _class_ needs to be abstract.  Not the _members_.  Other than that, it's the same test as `Class` gets.

**Comment by ajvincent** [comment]
[Playground Link](https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.2.2&ssl=33&ssc=3&pln=33&pc=8#code/JYWwDg9gTgLgBAbwFBzgQQEYGcZQIYDGMAwhAHY5QCuR0SAvnAGZQQhwBEMAnmAKYBaJnxwcA3EiShIsRHwAe-ImixZgAczJ4MAGz4AaOAqUwAolFZRDxvkQByEGCrWbte64tswAKrz6MWNjgAchgsABNgiSRjaHgefjgASSw0Mm4AHm8APjgAXjgABiN5GD4ycKw4AEY4ADI4bzgAfjhcKj44AC5mPB0sPmiEzuIdPFUAeR1wrMM0KHUqEHKwkrKKqqoyAGsyCAB3MgBtAF18uDx009yC5ABIMFYYRz8e7wk7sj59gAoAOgBeAWSxWWAA+j15otlmQwgBKN4SehDPxwUbjLB2b6zdDAmGrBTrSpwLa7A7HM4FS7ca7ne6PRwvfg9AAKwAI2xx2z43AgTEa2Q+X1+AL+QOhoIhuIlsKwCMaSOisVkwzRY1UOKhINla3KxNJe0Op3O1NpeRQbWonUJeqq7U6zQt6NUWP2mrxoNyXSd6qwUxm3jmHtlgskwFhfCgTEInUwlEIJF9-vdMoJpVtJJ2hopJquJ1yNo26GwuATpAo7VoUBT2rCuXpTyZfERDDDEajMeL8aIzsx2MD0trVUL+qz5ONVLzBfTRbjpZ75EoNGe1YHWvxWHrSAejeGrPZnIH3N5-JySMkyviqLn+B7vprG91RYN48pFyn5wt0f61pnxPtLQWjeZa+q6D6et0cBASWt6JhiyZrsGdbRNo3bwAQvpdvOMAAEJUMA0zhuoWTnC+hxbnc5KRlgLZ3AQi6ViuPwYPhhFkOoEyHNRbxwog253DAAAWwBYH8VFQFUBQsQR4REZxXwSR89CtkgGEYnAeEyURWTTkSVTAUQmlscROSIMpSCqsQ5RYFQkl8XREBbDAPRkEsGCRoqkhqaocAABKOQMGTyZGpBOU+xJWRQtnnJFNmbuFVRGbJ7FBVxUChbC9bmd5VTEMAPA4ToEAchkSVEb4iQjolrHJcRsW2dkFFQCIwDhOUBDNhpNXlX40QORW1BVj8-m2T1zJYbBvald17EVQYcBHPVWD5rxyCoOt605V1WnsQlfkBWNnQIMpdwCcJonNWobVkB15zCttxk-Ag9FOT0ABM9BwkpKn0RWcAAGJ4CABHcOcPz3XlBVFRyw0BXwcJwn8l2te1fBiWlWASDYRBzRkKRpJkwx8gDQMg41PzfgMX0xJ4yiqBoWi6HwGSuSA7lQNkPyA8DOjcH8L2wl9QA)

If  line 33 says `false extends true ?`, the test fails.  If line 33 says `true extends true`, the test passes.  Which is what I was aiming for.

**Pull request merged**
