### PR TITLE
Add missing exports for some of the TypeScript 4.1-only types

### PR DESCRIPTION
**Pull request by armedi**
The [documentation](https://github.com/sindresorhus/type-fest#template-literal-types) already listed these two utilities, but they are not exported yet from `ts41/index.d.ts`
- CamelCasedProperties
- CamelCasedPropertiesDeep

### CODE REVIEW

**Comment by sindresorhus** [comment]
There are many more missing: https://github.com/sindresorhus/type-fest/commit/c043c258f7cac8f355531a332a496181447c9d4f

// @wwwzbwcom

**Comment by wwwzbwcom** [comment]
> There are many more missing: [c043c25](https://github.com/sindresorhus/type-fest/commit/c043c258f7cac8f355531a332a496181447c9d4f)
> 
> // @wwwzbwcom

@sindresorhus 
Whoops, should I start another PR or can @armedi  help me fix these? thanks!

**Comment by sindresorhus** [comment]
@wwwzbwcom Do a new PR. This one doesn't seem to move forward.

**Comment by armedi** [comment]
hi @wwwzbwcom @sindresorhus,

I just added more missing exports for Typescript 4.1 special types

**Pull request merged**
