### PR TITLE
Add `KeyPath` and `PathValue` types

### LINKED ISSUE #147: Proposal: Key path type
For example, to correctly get the type of a nested property using a string key path: `get(object, 'foo.bar')`, like https://github.com/sindresorhus/dot-prop

I found this playground:
https://www.typescriptlang.org/play?ts=4.1.0-pr-40336-88#code/FAFwngDgpgBACgQxACwJIFsIBsA8AVAGhgGkowYoAPEKAOwBMBnGAazIHsAzGPAPhgC8wGCTIVqdJjEYgATgEtaAc2EwA-DwDapMAF1xNBswBKUAMbtZ9HDIXKiCWmF6qRGgD4wABgBIA3joAvgB0-ogoGNj42mS6RACilGZYAK70UDhsYFxaOnGsHNyOYJq6vPwAZNJyikqBXq4iMJ6+AWQh-onJaRlZOXgxekR9RU6lldV2dQ1NMABcMLRQAG5QsqoLS6uyANzAoJCw4WiYWABM+PwC8EgnUYQF2dx8zY-9ewfQNyiXgt9351+VEMUlstVeIx46n+kUBLwWkLwH3AX2OADUEKkMg84AZJMxjpcrqpccD8d5-IpOGtRGAOn4qTTTDJ6qoNDo8UY3s9GhpmSBOVJCQM8i5Zm5-hisdE8kR+WLxZsVmtGkrtht4ILmIjeVo4LpVYtlbt9ulkghZLBOClaGYQPJ2LQYEooCB8ERSRIucLygAKdgAIwAVgsHhBbgs4ABKSO3KUpbEe3gfCy0GQwQNB8wC65+VSceSyGQAOQQ6CgCwARAAReRQJTsSsEVRYBAlssVmCVgASCAAXk3VAgXQsAMwABmbIggsnYWbtjAWmkafkWHarpgQLHkICbMFTNQDKRAlkXMAAbAAOGCBKdNVe0dddgDCjpkSCge4PCiPJ6LCwARjOG87wNQIYDbfc3xAD4XRAf1g2zIhKxnOds0YYJx2CR9y0rKMdiAA

### PR DESCRIPTION
**Pull request by kainiedziela**
Fixes #147

[Playground link](https://www.typescriptlang.org/play?ts=4.1.0-pr-40336-88#code/FAFwngDgpgBACgQxACwJIFsIBsA8AVAGhgGkowYoAPEKAOwBMBnGAazIHsAzGPAPhgC8wGCTIVqdJjEYgATgEtaAc2EwA-DwDapMAF1xNBswBKUAMbtZ9HDIXKiCWmF6qRGgD4wABgBIA3joAvgB0-ogoGNj42mS6RACilGZYAK70UDhsYFxaOnGsHNyOYJq6vPwAZNJyikqBXq4iMJ6+AWQh-onJaRlZOXgxekR9RU6lldV2dQ1NMABcMLRQAG5QsqoLS6uyANzAoJCw4WiYWABM+PwC8EgnUYQF2dx8zY-9ewfQNyiXgt9351+VEMUlstVeIx46n+kUBLwWkLwH3AX2OADUEKkMg84AZJMxjpcrqpccD8d5-IpOGtRGAOn4qTTTDJ6qoNDo8UY3s9GhpmSBOVJCQM8i5Zm5-hisdE8kR+WLxZsVmtGkrtht4ILmIjeVo4LpVYtlbt9ulkghZLBOClaGYQPJ2LQYEooCB8ERSRIucLygAKdgAIwAVgsHhBbgs4ABKSO3KUpbEe3gfCy0GQwQNB8wC65+VSceSyGQAOQQ6CgCwARAAReRQJTsSsEVRYBAlssVmCVgASCAAXk3VAgXQsAMwABmbIggsnYWbtjAWmkafkWHarpgQLHkICbMFTNQDKRAlkXMAAbAAOGCBKdNVe0dddgDCjpkSCge4PCiPJ6LCwARjOG87wNQIYDbfc3xAD4XRAf1g2zIhKxnOds0YYJx2CR9y0rKMdiAA)

### KeyPath

Represents a dot path to a nested object property.

**Use case:** to be used in any helper function that extracts values based on a string dot path, like [lodash.get](https://lodash.com/docs/#get) or [dot-prop](https://github.com/sindresorhus/dot-prop).

### PathValue

Targets a property from a nested object using a dot path.

**Use case:** Extracting a given value from a complex API requests that is otherwise non-essential outside that value.

### Example

```TS
declare function get<T, P extends KeyPath<T>>(obj: T, path: P): PathValue<T, P>;
const user = {
  firstName: 'Foo',
  lastName: 'Bar',
  projects: [
    { name: 'Baz', contributors: 68 },
    { name: 'Waldo', contributors: 12 },
  ]
};

get(user, 'projects.0.name');
```

### CODE REVIEW

**Comment by kainiedziela** [comment]
These types will only work on TS 4.1 and up, so some checks will not be successful.

**Comment by sindresorhus** [comment]
I did you see https://github.com/sindresorhus/type-fest/pull/153 ?

**Comment by kainiedziela** [comment]
I did not. Makes this obsolete I guess.

**Comment by sindresorhus** [comment]
Yeah, sorry. It was first so I'm going to go with that. Would be great if you could help review https://github.com/sindresorhus/type-fest/pull/153.

**Pull request closed without merging**
