### PR TITLE
Fix support for readonly and generic arrays in the `LastArrayElement` type

### LINKED ISSUE #265: `LastArrayElement<string[]>` emits `never`
[playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAyBDAzjAglKDRAUQBtgBbYAOxgB4A1DUgV2ABVlVQYaATLHCjAMfCNVKI4LagGtqEAO7UA2gF0AfHAC8AKACQTVhy5we-QSoCW1AGbAocMpRoxOKNQf0B+J+Sq07sBeAFxwRmxBZiC81AJw1nYOcAD6ADRwAHTZNvaO7BhWpJ76pb6YOPiEJP6udAVFGl76YdTAAG4OANy6uqCQsAimAJIwAMoAFhAspHwAQsBjMFA2AOY66Nh4BETOAfQ4K9Sr6k1AA)

fixed version

```ts
export type LastArrayElement<
  ValueType extends readonly unknown[]
> = ValueType extends [infer ElementType]
  ? ElementType
  : ValueType extends [infer _, ...infer Tail]
  ? LastArrayElement<Tail>
  : ValueType extends Array<infer ElementType>
  ? ElementType
  : never

export type ItShouldBeString = LastArrayElement<string[]>
```

[playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAyBDAzjAglKDRAUQBtgBbYAOxgB4A1DUgV2ABVlVQYaATLHCjAMfCNVKI4LagGtqEAO7UA2gF0AfHAC8AKACQTVhy5we-QSoCW1AGbAocMpRoxOKNQf0B+J+Sq07sBeAFxwRmxBZiC81AJw1nYOcAD6ADRwAHTZNvaO7BhWpJ76pb6YOPiEJP6udAVFGl76YREmKNGx8VVEdLnJzgFuXFq+g65BYdTAAG4OANy6uqCQsAimAJIwAMoAFhAspHwAQsDbMFA2AOY66Nh4BETjtHQ4l9RX6k1AA)

### PR DESCRIPTION
**Pull request by JounQin**
Fixes #265

### CODE REVIEW

**Comment by sindresorhus** [comment]
Tests are failing

**Comment by sindresorhus** [comment]
Can you explain your changes?

**Comment by JounQin** [comment]
> Tests are failing

Sorry, I'll take a look

> Can you explain your changes?

Does the issue explain already?

**Comment by sindresorhus** [comment]
> Does the issue explain already?

It did not. It's usually helpful to have one or two sentences explaining the issue instead of assuming that a code example is clear enough.

> It fixs readonly Array and T[].

This makes it clear. Thanks.

**Pull request merged**
