### PR TITLE
`PartialDeep`: Skip constructor

### PR DESCRIPTION
**Pull request by Emiyaaaaa**
- related #728

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks!

@Emiyaaaaa You have done a lot of good work here. Would you be interested in becoming a maintainer? No worries if not.

**Comment by Emiyaaaaa** [comment]
> Thanks!
> 
> @Emiyaaaaa You have done a lot of good work here. Would you be interested in becoming a maintainer? No worries if not.

Sure! I'd like that, but still need your suggest in most of decision and last check of pull request before merge for now.

**Comment by sindresorhus** [comment]
Awesome!

--

> but still need your suggest in most of decision and last check of pull request before merge for now.

Yeah, I prefer pull request driven development. It's always good to get another pair of eyes looking at changes.

**Comment by Emiyaaaaa** [comment]
> Awesome!
> 
> --
> 
> > but still need your suggest in most of decision and last check of pull request before merge for now.
> 
> Yeah, I prefer pull request driven development. It's always good to get another pair of eyes looking at changes.

Sorry, I mean I can review other pull request but need you review again before merge.

**Pull request merged**
