### PR TITLE
Add `PackageJson.PublishConfig` type

### LINKED ISSUE #204: PackageJson type does not contain known properties for "publishConfig"
publishConfig is set to:
https://github.com/sindresorhus/type-fest/blob/532e1da01650382e6989c407fc83918ab5e72fff/source/package-json.d.ts#L574

I believe the publishConfig should have `access`, `registry`, and `tag`.

### PR DESCRIPTION
**Pull request by ryansonshine**
This change adds the interface for the PackageJson.PublishConfig.

Closes #204

### CODE REVIEW

**Comment by sindresorhus** [comment]
According to https://docs.npmjs.com/cli/v7/configuring-npm/package-json#publishconfig, it supports a lot more properties.

**Comment by ryansonshine** [comment]
@sindresorhus Ah good catch, when I initially read that I thought the config options applied to other sections in package.json as a whole. I'll do some additional digging and submit an update

**Comment by ryansonshine** [comment]
I added the type to allow for additional props in general, per https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/package.json#L576-L591

**Review by ryansonshine — COMMENTED** [review]
Looks good to me

**Pull request merged**
