### PR TITLE
Add `Url2Json` type

### PR DESCRIPTION
**Pull request by Asarua**
Is a type that gets the query string from the URL

### CODE REVIEW

**Comment by sindresorhus** [comment]
What's the use-case?

**Comment by Asarua** [comment]
> What's the use-case?

Sorry, let me complete it

Required: Typescript > 4.1

Here is the demo code

```typescript
const url = 'https://google.com?a=1&b=2'

type QueryString = Url2Json<typeof url>
```

it will be

```typescript
{
    a: "1",
    b: "2"
}
```

**Comment by sindresorhus** [comment]
It's a cute idea, but I don't see how it will work in real-life scenarios. I doesn't and cannot handle escaping, which most URLs have:

```js
const url = 'https://google.com?a=1%20foo&b=2'
```

Also, with most request libraries, you pass the query parameters as an object, not in the actual URL.

**Comment by Asarua** [comment]
I use this method to obtain URL parameters, because many projects I contact need this step. I think I should not be the only one with this requirement.

Similarly, it can also make the type of our request library more perfect.

**Comment by voxpelli** [comment]
I think question is:

Why in that use case is a URL string literal the basis for the types?

Take fastify [as an example](https://github.com/fastify/fastify/blob/main/docs/TypeScript.md#using-generics):

```typescript
interface IQuerystring {
  a: string;
  b: number;
}

server.get<{
  Querystring: IQuerystring,
}>('/auth', async (request, reply) => {
  const { a, b } = request.query
  // The a and b will have the correct types inferred
})
```

The only thing you can infer from a URL string literal query parameters that themselves are string literals, and static query parameters are not that different from the path sections in the URL?

Most query parameters are dynamic, so an approach like Fastify's seems like the more typical approach to this for me (but I'll happily hear more examples to prove me wrong)

(For the sake of completeness, my own approach with Fastify was actually a bit more complex, I sent in a JSON Schema to validate the query parameters and then used [`json-schema-to-typescript`](https://www.npmjs.com/package/json-schema-to-typescript) to generate types from those schemas, thus actually knowing for a fact that my routes never got any other data than the ones my types expected)

**Comment by sindresorhus** [comment]
We are unfortunately not going to accept this type.

Next time, I recommend opening an issue first for discussion so you don't have to have your effort go in vain.

**Comment by skarab42** [comment]
> (For the sake of completeness, my own approach with Fastify was actually a bit more complex, I sent in a JSON Schema to validate the query parameters and then used [`json-schema-to-typescript`](https://www.npmjs.com/package/json-schema-to-typescript) to generate types from those schemas, thus actually knowing for a fact that my routes never got any other data than the ones my types expected)

FI: @voxpelli I have made a [Fastify tRPC adapter](https://trpc.io/docs/fastify) to make this process more easier ;)

**Comment by Space-yg** [comment]
Hi @Asarua, I have been inspired by your request, so for the past couple of weeks, I have been working on it and I made it real here:
- Github: https://github.com/Space-yg/space.types
- npm: https://www.npmjs.com/package/space.types

_(Pssst, it can escape characters too)_

**Pull request closed without merging**
