### PR TITLE
Add `Jsonify` support for optional object keys

### PR DESCRIPTION
**Pull request by skarab42**
This PR adds support for optional object keys

Related to #424

### CODE REVIEW

**Comment by sindresorhus** [comment]
// @frontsideair

**Review by frontsideair — APPROVED** [review]
I'm really happy with the changes and the current test coverage. I also plugged this branch to Remix and it fixes relevant tests. (There are only two test cases that are failing, irrelevant to this PR. For those curious: "supports plain Response" and "transforms unserializables to null in arrays".)

Let's go ahead and merge this. Thanks a lot for picking this up and great delivery!

**Comment by pcattori** [comment]
> I also plugged this branch to Remix and it fixes relevant tests. (There are only two test cases that are failing, irrelevant to this PR. For those curious: "supports plain Response" and "transforms unserializables to null in arrays".)

@frontsideair : to be clear, were there failing tests for this in the Remix codebase? AFAIK, we've only been merging PRs with all passing tests (with minor exceptions for Windows compatibility tests).

Or are the failing tests you are referring to elsewhere?

**Comment by frontsideair** [comment]
Sorry for the confusion, I was talking about using Jsonify from this repo instead of the one in Remix repo, which I hope will replace it soon. There are no failing test in Remix afaict.

**Pull request merged**
